# Regression tests for the files in this directory. See run_expects.py.

tests = [
    {'type': 'check', 'name': 'fba', 'expect': 'OK'},
    {'type': 'check', 'name': 'interpdef1',
     'expect': 'interpdef1.ivy: line 5: error: definition of interpreted symbol <'},
    {'type': 'check', 'name': 'whileexists1', 'expect': 'OK'},
    {'type': 'check', 'name': 'whilesome1', 'expect': 'OK'},
    {'type': 'check', 'name': 'whilesome2', 'expect': 'OK'},
    {'type': 'check', 'name': 'fundef1',
     'expect': 'error: Variable Y:t occurs free on right-hand side of definition'},
    {'type': 'check', 'name': 'fundef2',
     'expect': 'error: Variable X:t occurs twice on left-hand side of definition'},
    {'type': 'check', 'name': 'strat1',
     'expect': 'error: The verification condition is not in'},
    {'type': 'check', 'name': 'skolem1', 'expect': 'error: failed checks: 1'},
    {'type': 'check', 'name': 'ifstar1', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag1', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag2',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag3', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag4',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag5', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag6', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag7',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag8',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag9',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag10',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag11', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag12', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag13', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag14',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag15',
     'expect': 'An interpreted symbol is applied to a universally quantified variable'},
    {'type': 'check', 'name': 'frag16', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag17', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag18', 'expect': 'OK'},
    {'type': 'check', 'name': 'frag19', 'expect': 'OK'},
    {'type': 'check', 'name': 'oddeven', 'args': ['complete=fo'], 'expect': 'OK'},
    {'type': 'check', 'name': 'oddeven2', 'args': ['complete=fo'], 'expect': 'OK'},
    {'type': 'check', 'name': 'oddeven3', 'expect': 'OK'},
    {'type': 'check', 'name': 'oddeven4', 'expect': 'OK'},
    {'type': 'check', 'name': 'learning_switch1', 'args': ['trace=true'],
     'expect': 'learning_switch1.ivy: line 37:'},
    {'type': 'check', 'name': 'ded1', 'expect': 'OK'},
]
