# Regression tests for the files in this directory. See run_expects.py.

tests = [
    # ivy_check
    {'type': 'check', 'name': 'account2', 'expect': 'OK'},
    {'type': 'check', 'name': 'account3', 'expect': 'OK'},
    {'type': 'check', 'name': 'account', 'expect': 'OK'},
    {'type': 'check', 'name': 'array1', 'expect': 'error: Some assertions are not checked'},
    {'type': 'check', 'name': 'arrayset2', 'expect': 'OK'},
    {'type': 'check', 'name': 'arrayset3', 'expect': 'OK'},
    {'type': 'check', 'name': 'arrayset', 'expect': 'OK'},
    {'type': 'check', 'name': 'client_server_example', 'expect': 'OK'},
    {'type': 'check', 'name': 'counter_example',
     'expect': 'counter_example.ivy: line 54: guarantee ... FAIL'},
    {'type': 'check', 'name': 'coveragefail',
     'expect': 'error: Some assertions are not checked'},
    {'type': 'check', 'name': 'helloworld', 'expect': 'OK'},
    {'type': 'check', 'name': 'interference2', 'expect': 'OK'},
    {'type': 'check', 'name': 'interference3', 'expect': 'OK'},
    {'type': 'check', 'name': 'interference4', 'expect': 'OK'},
    {'type': 'check', 'name': 'interference',
     'expect': 'error: Call out to right_player.intf_ping'},
    {'type': 'check', 'name': 'leader_election_ring2',
     'expect': 'error: Some assertions are not checked'},
    {'type': 'check', 'name': 'leader_election_ring_btw',
     'expect': 'leader_election_ring_btw.ivy: line 118: guarantee ... FAIL'},
    {'type': 'check', 'name': 'leader_election_ring',
     'expect': 'leader_election_ring.ivy: line 114: guarantee ... FAIL'},
    {'type': 'check', 'name': 'leader_election_ring_repl', 'expect': 'OK'},
    {'type': 'check', 'name': 'leader_election_ring_udp2', 'expect': 'OK'},
    {'type': 'check', 'name': 'leader_election_ring_udp', 'expect': 'OK'},
    {'type': 'check', 'name': 'lesstrivnet', 'expect': 'OK'},
    {'type': 'check', 'name': 'modparam_example', 'expect': 'OK'},
    {'type': 'check', 'name': 'object_example', 'expect': 'OK'},
    {'type': 'check', 'name': 'paraminit2', 'expect': 'OK'},
    {'type': 'check', 'name': 'paraminit3', 'expect': 'OK'},
    {'type': 'check', 'name': 'paraminit', 'args': ['isolate=iso_foo'], 'expect': 'OK'},
    {'type': 'check', 'name': 'pingpongclock', 'expect': 'OK'},
    {'type': 'check', 'name': 'pingpong', 'expect': 'OK'},
    {'type': 'check', 'name': 'po_example', 'expect': 'OK'},
    {'type': 'check', 'name': 'timeout_test', 'expect': 'OK'},
    {'type': 'check', 'name': 'trivnet', 'expect': 'OK'},
    {'type': 'check', 'name': 'udp_test2', 'expect': 'OK'},
    {'type': 'check', 'name': 'udp_test', 'expect': 'OK'},
    {'type': 'check', 'name': 'list_reverse', 'expect': 'OK'},
    {'type': 'check', 'name': 'indexset', 'expect': 'OK'},
    {'type': 'check', 'name': 'number_theory', 'expect': 'OK', 'group': 'unreliable'},

    # repl (ivy_to_cpp target=repl); expect is the expect-module name, or
    # omitted to use "<name>_expect"
    {'type': 'repl', 'name': 'leader_election_ring_repl', 'args': ['isolate=iso_impl'],
     'expect': 'leader_election_ring_repl_iso_impl_expect'},
    {'type': 'repl', 'name': 'helloworld'},
    {'type': 'repl', 'name': 'account'},
    {'type': 'repl', 'name': 'account2'},
    {'type': 'repl', 'name': 'account3'},
    {'type': 'repl', 'name': 'leader_election_ring_repl'},
    {'type': 'repl', 'name': 'udp_test', 'args': ['isolate=iso_impl']},
    {'type': 'repl', 'name': 'udp_test2', 'args': ['isolate=iso_impl']},
    {'type': 'repl', 'name': 'leader_election_ring_udp', 'args': ['isolate=iso_impl']},
    {'type': 'repl', 'name': 'timeout_test'},
    {'type': 'repl', 'name': 'leader_election_ring_udp2', 'args': ['isolate=iso_impl']},
    {'type': 'repl', 'name': 'paraminit', 'args': ['isolate=iso_foo']},
    {'type': 'repl', 'name': 'paraminit3', 'args': ['isolate=iso_foo']},

    # to_cpp (ivy_to_cpp compilation diagnostics)
    {'type': 'to_cpp', 'name': 'leader_election_ring_repl_err',
     'args': ['target=repl', 'isolate=iso_impl'],
     'expect': 'error: relevant axiom asgn.injectivity not enforced'},
    {'type': 'to_cpp', 'name': 'leader_election_ring_repl_err2',
     'args': ['target=repl', 'isolate=iso_impl'],
     'expect': 'error: No implementation for action node.get_next'},
    {'type': 'to_cpp', 'name': 'leader_election_ring_udp2_warn',
     'args': ['target=repl', 'isolate=iso_impl'],
     'expect': 'warning: action sec.timeout is implicitly exported'},
    {'type': 'to_cpp', 'name': 'paraminit', 'args': ['target=repl'],
     'expect': 'error: cannot compile initial constraint on "foo.bit" because type t is large. suggest using "after init"'},
    {'type': 'to_cpp', 'name': 'paraminit2', 'args': ['target=repl', 'isolate=iso_foo'],
     'expect': 'initial condition depends on stripped parameter'},
]
