#!/usr/bin/env bash
# Simulator for INPUT-DRIVEN decomposition designs (complex3_cmax_dec.ivy and
# the other single-input pipelines).  Unlike the reference-tagging and
# stage-decomposition CPUs -- which fetch from a memory -- these designs receive
# one instruction per cycle on the primary input `inst_in`; the environment must
# HOLD that input while the pipeline stalls.
#
# So we cannot inject a program into a memory (there is none).  Instead we build
# a closed-system feedback harness in Verilog: a small program ROM feeds
# `inst_in`, and the instruction pointer advances only when the design is not
# stalling.  This requires the design's stall wire to be observable, so we first
# `expose` it as a port.
#
#   ./sim_cpu_input.sh <design[.ivy]> [prog.hex] [cycles] [stall_sig] [extra_signals]
#
#     design         design base name or .ivy path (default complex3_cmax_dec)
#     prog.hex       program as hex instruction words, one per line (default cmax_prog.hex)
#     cycles         number of clock cycles to simulate           (default 40)
#     stall_sig      name of the pipeline's issue-stall wire      (default issue_stall)
#     extra_signals  comma-separated extra signal names to tabulate per cycle
#                    (matched by suffix, e.g. "r"); the stall signal is always shown
#
# Pipeline: ivy_to_rtl -> expose the stall wire -> generate a feedback harness
# with the program in a ROM -> yosys (flatten) sim -> VCD.  Prints a per-cycle
# table of the requested signals.
set -e
cd "$(dirname "$0")"

DESIGN="${1:-complex3_cmax_dec}"
BASE="$(basename "${DESIGN%.ivy}")"        # strip dir and .ivy -> base name
PROG="${2:-cmax_prog.hex}"
CYCLES="${3:-40}"
STALL="${4:-issue_stall}"
EXTRA="${5:-r}"

[ -f "$BASE.ivy" ] || { echo "no such design: $BASE.ivy" >&2; exit 1; }
[ -f "$PROG" ]     || { echo "no such program: $PROG"    >&2; exit 1; }

# 1. Emit RTLIL (ivy_to_rtl writes <BASE>.il).
ivy_to_rtl "$BASE.ivy" >/dev/null

# 2. Determine the instruction word width from the emitted \inst_in port.
W=$(grep -oE 'wire width [0-9]+ input [0-9]+ \\inst_in' "$BASE.il" \
        | grep -oE '[0-9]+' | head -1)
W="${W:-8}"

# 3. Generate the feedback harness (program ROM + pointer that advances only on
#    ~stall) as Verilog.  The design's implementation top is `cpu`.
python3 - "$PROG" "$W" "$STALL" > "${BASE}_tb.v" <<'PY'
import sys
prog = [l.split('#')[0].strip() for l in open(sys.argv[1])]
prog = [p for p in prog if p]
w = int(sys.argv[2]); stall = sys.argv[3]
n = len(prog); aw = max(1, (n - 1).bit_length())
print("// generated by sim_cpu_input.sh -- do not edit")
print("module sim_top(input clk, input rst);")
print("   reg [%d:0] ptr;" % (aw - 1))
print("   reg [%d:0] prog [0:%d];" % (w - 1, n - 1))
print("   wire [%d:0] inst = prog[ptr];" % (w - 1))
print("   wire stall;")
print("   cpu dut(.inst_in(inst), .%s(stall), .\\posedge (clk), .rst(rst));" % stall)
print("   always @(posedge clk)")
print("     if (rst)         ptr <= %d'd0;" % aw)
print("     else if (~stall)  ptr <= ptr + %d'd1;" % aw)
print("   initial begin")
for i, p in enumerate(prog):
    print("     prog[%d]=%d'h%s;" % (i, w, p.lower().lstrip('0x') or '0'))
print("     ptr = %d'd0;" % aw)
print("   end")
print("endmodule")
PY

# 4. Simulate.  Expose the stall wire on `cpu`, link the harness, flatten, sim.
yosys -q -p "read_rtlil ${BASE}.il; hierarchy -top cpu; expose cpu/w:${STALL}; \
             read_verilog ${BASE}_tb.v; hierarchy -top sim_top; flatten; proc; \
             memory_collect; sim -clock clk -reset rst -n ${CYCLES} -vcd ${BASE}.vcd"

# 5. Report.  Signal names in the flattened VCD carry a stage prefix, so requested
#    names are matched by suffix: a name `s` matches a VCD signal `s` or `*.s`.
python3 - "${BASE}.vcd" "$STALL" "$EXTRA" <<'PY'
import sys, re
vcd = open(sys.argv[1]).read()
want = [sys.argv[2]] + [s for s in sys.argv[3].split(',') if s]

def matches(name, s):
    return name == s or name.endswith('.' + s)

code = {}
for m in re.finditer(r'\$var\s+\w+\s+(\d+)\s+(\S+)\s+(\S+?)(?:\s+\[[^\]]*\])?\s+\$end', vcd):
    w, c, name = int(m.group(1)), m.group(2), m.group(3)
    for s in want:
        if s not in code and matches(name, s):
            code[s] = c
missing = [s for s in want if s not in code]
if missing:
    print("  (signals not found, skipped: %s)" % ', '.join(missing))

rev = {c: n for n, c in code.items()}
def val(bits):
    return int(bits, 2) if set(bits) <= set('01') else 'x'

cur = {n: 'x' for n in code}
snaps = []; t = 0
def snap():
    if snaps and snaps[-1][0] == t: snaps[-1] = (t, dict(cur))
    else: snaps.append((t, dict(cur)))
for line in vcd.splitlines():
    if line.startswith('#'):
        snap(); t = int(line[1:])
    elif line[:1] == 'b':
        mm = re.match(r'b([01xzZ]+)\s+(\S+)$', line)
        if mm and mm.group(2) in rev: cur[rev[mm.group(2)]] = val(mm.group(1))
    elif line[:1] in '01xzZ' and len(line) >= 2:
        c = line[1:]
        if c in rev: cur[rev[c]] = int(line[0]) if line[0] in '01' else 'x'
snap()

names = [n for n in want if n in code]

# Collapsed trace of the first reported (non-stall) signal, with stall cycles
# collapsed -- like the pc trace in sim_cpu_dec.sh, for easy regression grep.
edges = [(tt, v) for tt, v in snaps if tt % 10 == 0]
extra = [n for n in names if n != sys.argv[2]]
if extra:
    s = extra[0]
    seq, prev = [], object()
    for _, v in edges:
        if v[s] != 'x' and v[s] != prev:
            seq.append(v[s]); prev = v[s]
    print("=== %s trace (collapsed) ===" % s)
    print("  " + " -> ".join(str(x) for x in seq))
stalled = any(v[sys.argv[2]] == 1 for _, v in edges)
print("=== stalls observed: %s ===" % ("yes" if stalled else "no"))

print("=== per-cycle signals (sampled at clock edges) ===")
print("  " + "  ".join(f"{n:>12}" for n in ['t'] + names))
prevrow = None
for tt, v in snaps:
    if tt % 10:            # the VCD emits half-cycle ticks; sample on the edge
        continue
    row = tuple(v[n] for n in names)
    if row == prevrow: continue      # collapse unchanged rows
    prevrow = row
    print("  " + "  ".join([f"{tt:>12}"] + [f"{str(v[n]):>12}" for n in names]))
PY
